In [1]:
import matplotlib
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
a = np.array([1, 2, 3])
print(a)  # 输出: [1 2 3]

[1 2 3]


In [12]:
b = np.array([1, 2, 3], dtype=float)
print(f"数组维度:{b.shape},维度数量:{b.ndim},元素个数:{b.size}")
print(b)  # 输出: [1. 2. 3.]

数组维度:(3,),维度数量:1,元素个数:3
[1. 2. 3.]


In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(f"数组维度:{b.shape},维度数量:{b.ndim},元素个数:{b.size}")
print(b[0, 1])  # 第一行第二列: 2
print(b[1, :])  # 第二行所有列: [4 5 6]

数组维度:(2, 3),维度数量:2,元素个数:6
2
[4 5 6]


In [13]:
# 基础运算

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # 加法: [5 7 9]
print(a * b)  # 逐元素乘法: [4 10 18]
print(a.dot(b))  # 点积: 32

[5 7 9]
[ 4 10 18]
32


In [14]:
# 聚合函数
print(np.sum(a))  # 总和: 6
print(np.mean(a))  # 平均值: 2.0
print(np.max(a))  # 最大值: 3
print(np.min(a))  # 最小值: 1

6
2.0
3
1


In [17]:
a = np.arange(6)
# 改变数组形状而不改变数据
b = a.reshape((3, 2))
print(a)
print(b)

# 将多维数组展平为一维
c = b.flatten()
print(c)  # 输出: [0 1 2 3 4 5]

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
# 数组创建

