In [41]:
import matplotlib
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [48]:
a = np.arange(12)
a = a + 100
a = a.reshape(3, 4)
print(a)

print(f"a shape:{a.shape}, ndim:{a.ndim}")

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
a shape:(3, 4), ndim:2


In [56]:
# 二维数组边缘填充0,宽度s
def padding(a, s = 1):
    a = a.copy()
    #先加行
    rows = np.zeros((s, a.shape[1]), dtype="uint8")
    #再加列，这时候列长已经扩充 2*s
    columns = np.zeros((a.shape[0] +(2 * s), s), dtype="uint8")
    #拼接
    img = np.vstack((rows, a, rows))
    img = np.hstack((columns, img, columns))
    return img

aNew = padding(a, 2)
print(aNew)
print(f"aNew shape:{aNew.shape}, ndim:{aNew.ndim}")

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0 100 101 102 103   0   0]
 [  0   0 104 105 106 107   0   0]
 [  0   0 108 109 110 111   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
aNew shape:(7, 8), ndim:2
